version: '3.8'

services:
  mysql:
    build: ./docker-mysql
    container_name: docker-mysql
    ports:
      - "3306:3306"
    volumes:
      - "./docker-mysql/conf/:/etc/mysql/conf.d"
      - "./docker-mysql/data/:/var/lib/mysql"
    env_file: "./docker-mysql/mysql.env"
    environment:
      TZ: "Asia/Tokyo"
    restart: always
    networks:
      - app-net

  phpmyadmin:
    build: ./docker-phpmyadmin
    container_name: docker-phpmyadmin
    links:
      - mysql:mysql
    ports:
      - "8021:80"
    volumes:
      - "./docker-phpmyadmin/sessions:/sessions"
    environment:
      PMA_ARBITRARY: "1"
      PMA_HOST: "mysql"
      PMA_USER: "root"
      PMA_PASSWORD: "root"
    restart: always
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
